# Use the official MySQL 8.0 image as the base image
FROM mysql:8.0

# Set the root password for MySQL (change it to a secure password)
ENV MYSQL_ROOT_PASSWORD=contrasena

# Set the character set and collation for MySQL (optional)
ENV MYSQL_DATABASE=db_raza
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=contrasena

#CMD ["/entrypoint.sh"]
